// <auto-generated />
using System;
using Logins.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logins.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220908041353_intial")]
    partial class intial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Logins.Domain.Classes.Lookup", b =>
                {
                    b.Property<int>("LookupId")
                        .HasColumnType("int");

                    b.Property<int>("LookupTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("LookupId", "LookupTypeId");

                    b.ToTable("Lookup");

                    b.HasData(
                        new
                        {
                            LookupId = 1,
                            LookupTypeId = 1,
                            Caption = "Admin"
                        },
                        new
                        {
                            LookupId = 2,
                            LookupTypeId = 1,
                            Caption = "Default"
                        },
                        new
                        {
                            LookupId = 1,
                            LookupTypeId = 2,
                            Caption = "CEO"
                        },
                        new
                        {
                            LookupId = 2,
                            LookupTypeId = 2,
                            Caption = "CMO"
                        },
                        new
                        {
                            LookupId = 3,
                            LookupTypeId = 2,
                            Caption = "HR Manager"
                        },
                        new
                        {
                            LookupId = 4,
                            LookupTypeId = 2,
                            Caption = "Sales Assistant"
                        },
                        new
                        {
                            LookupId = 5,
                            LookupTypeId = 2,
                            Caption = "HR Assistant"
                        },
                        new
                        {
                            LookupId = 6,
                            LookupTypeId = 2,
                            Caption = "IT Manager"
                        });
                });

            modelBuilder.Entity("Logins.Domain.Classes.LookupType", b =>
                {
                    b.Property<int>("LookupTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LookupTypeId"), 1L, 1);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("LookupTypeId");

                    b.ToTable("LookupType");

                    b.HasData(
                        new
                        {
                            LookupTypeId = 1,
                            Caption = "UserType"
                        },
                        new
                        {
                            LookupTypeId = 2,
                            Caption = "Position"
                        });
                });

            modelBuilder.Entity("Logins.Domain.Classes.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Locked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SignupDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 9, 8, 8, 43, 53, 218, DateTimeKind.Local).AddTicks(5283));

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = -1,
                            Address = "",
                            BirthDate = new DateTime(2022, 9, 8, 8, 43, 53, 218, DateTimeKind.Local).AddTicks(6746),
                            Email = "mahdi@goodlawsoftware.co.uk",
                            FirstName = "mahdi",
                            HireDate = new DateTime(2022, 9, 8, 8, 43, 53, 218, DateTimeKind.Local).AddTicks(6747),
                            LastName = "joveyni",
                            Locked = false,
                            Password = "47cd985a73d1af0f0ee2283437fb0176",
                            PositionId = 0,
                            SignupDate = new DateTime(2022, 9, 8, 8, 43, 53, 218, DateTimeKind.Local).AddTicks(6737),
                            UserTypeId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
